CREATE TABLE IF NOT EXISTS `#__programacion_peliculas` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`created_by` INT(11)  NOT NULL ,
`programa` VARCHAR(20) ,
`titulo` VARCHAR(50)  ,
`fhemision` DATE ,
`horainicio` TIME ,
`horafin` TIME ,
`duracion` SMALLINT(6)  ,
`tipo` VARCHAR(10)  ,
`detalle` TEXT(1500)  ,
`imagen` VARCHAR(20) ,
`video` VARCHAR(20) ,
`calificacion` VARCHAR(10) ,
`destacado` BOOLEAN ,
`enlace` VARCHAR(200) ,
`genero` VARCHAR(20) ,
`nacionalidad` VARCHAR(20) ,
`anio` YEAR ,
`idiomas` VARCHAR(20) ,
`director` VARCHAR(255) ,
`produccion` VARCHAR(255) ,
`interpretes` VARCHAR(255) ,
`guion` VARCHAR(255) ,
`fotografia` VARCHAR(255) ,
`musica` VARCHAR(255)  ,
`montaje` VARCHAR(255) ,
`realizacion` VARCHAR(255)  ,
`caratula` VARCHAR(20) ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

